In [49]:
# Load the "osmdata" package for mapping
library(osmdata)
library(ggplot2)
library(sf)
library(dplyr)

In [ ]:
Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright

In [50]:
# Colorado craft = sawmill
sawmill_cocr <- getbb("Colorado, USA") %>%
  opq(timeout = 120)%>%
  add_osm_feature(key = "craft",
                  value = "sawmill") %>%
  osmdata_sf()

coords <- sawmill_cocr$osm_points |> st_coordinates()
coords[, 2:1]

ERROR: Error in check_for_error(paste0(doc)): General overpass server error; returned:
The data included in this document is from www.openstreetmap.org. The data is made available under ODbL. runtime error: Query timed out in "query" at line 4 after 122 seconds. 


In [45]:
# Colorado industrial = sawmill
sawmill_coin <- getbb("Colorado, USA") %>%
  opq(timeout = 120)%>%
  add_osm_feature(key = "industrial",
                  value = "sawmill") %>%
  osmdata_sf()

coords <- sawmill_coin$osm_points |> st_coordinates()
coords[, 2:1]
nrow(coords)

[,1] [,2]

[1] 0

In [46]:
# Wyoming craft = sawmill
sawmill_wycr <- getbb("Wyoming, USA") %>%
  opq(timeout = 120)%>%
  add_osm_feature(key = "craft",
                  value = "sawmill") %>%
  osmdata_sf()

coords <- sawmill_wycr$osm_points |> st_coordinates()
coords[, 2:1]
nrow(coords)

[,1] [,2]

[1] 0

In [44]:
# Wyoming industrial = sawmill
sawmill_wyin <- getbb("Wyoming, USA") %>%
  opq(timeout = 120)%>%
  add_osm_feature(key = "industrial",
                  value = "sawmill") %>%
  osmdata_sf()

coords <- sawmill_wyin$osm_points |> st_coordinates()
coords[, 2:1]
nrow(coords)

[,1] [,2]

[1] 0